//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneRosterSampleDataGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneRosterSampleDataGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR00000,HOMEROOM KG,FY
        ///HR00001,HOMEROOM 01,FY
        ///HR00002,HOMEROOM 02,FY
        ///HR00003,HOMEROOM 03,FY
        ///HR00004,HOMEROOM 04,FY 
        ///HR00005,HOMEROOM 05,FY 
        ///HR00006,HOMEROOM 06,FY 
        ///HR00007,HOMEROOM 07,FY
        ///HR00008,HOMEROOM 08,FY
        ///HR00009,HOMEROOM 09,FY
        ///HR00010,HOMEROOM 10,FY
        ///HR00011,HOMEROOM 11,FY
        ///HR00012,HOMEROOM 12,FY
        ///0191100,ENGLISH KG,FY
        ///0101100,ENGLISH 01,FY
        ///0102100,ENGLISH 02,FY
        ///0103100,ENGLISH 03,FY
        ///0104100,ENGLISH 04,FY
        ///0105100,ENGLISH 05,FY
        ///0106100,ENGLISH 06,FY
        ///0107100,ENGLISH 07,FY
        ///0108100,ENGLI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string courses {
            get {
                return ResourceManager.GetString("courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ada
        ///Aeryn
        ///Alia
        ///Amidala
        ///Ayala
        ///Bail
        ///Bishop
        ///Bria
        ///Buck
        ///Buffy
        ///Cade
        ///Clover
        ///Dash
        ///Davin
        ///Deanna
        ///Dejah
        ///Deliah
        ///Diva
        ///Dutch
        ///Elihu
        ///Flash
        ///Fox
        ///Gaius
        ///Galen
        ///Holden
        ///Joelle
        ///Jubal
        ///Kaidan
        ///Katniss
        ///Kaylee
        ///Kerr
        ///Keyan
        ///Kira
        ///Korben
        ///Kylo
        ///Lazarus
        ///Leia
        ///Londo
        ///Lorelei
        ///Lyta
        ///Mal
        ///Max
        ///Motoko
        ///Moya
        ///Neo
        ///Pallas
        ///Reaver
        ///Ren
        ///Riddick
        ///Ripley
        ///River
        ///Roy
        ///Rune
        ///Samara
        ///Scorpius
        ///Sela
        ///Selim
        ///Serenity
        ///Serra
        ///Tali
        ///Talon
        ///Talyn
        ///Tasha
        ///Tetsuo
        ///Thane
        ///Trinity
        ///Tuck
        ///Tyrell
        ///Wikus
        ///Winter
        ///Zed
        ///Zhora
        ///Zira
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string firstnames {
            get {
                return ResourceManager.GetString("firstnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KG
        ///01
        ///02
        ///03
        ///04
        ///05
        ///06
        ///07
        ///08
        ///09
        ///10
        ///11
        ///12.
        /// </summary>
        internal static string grades {
            get {
                return ResourceManager.GetString("grades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anthold
        ///Scolee
        ///Waltev
        ///Reedav
        ///Denny
        ///Hezal
        ///Waltev
        ///Ardson
        ///Bobby
        ///Campbarn
        ///Wayny
        ///Colee
        ///Redy
        ///Wooders
        ///Damy
        ///Stayly
        ///Douglie
        ///Gramith
        ///Timy
        ///Cotte
        ///Chrewalt
        ///Amez
        ///Bertin
        ///Jamart
        ///Joshua
        ///Lenes
        ///Rony
        ///Murphy
        ///Damy
        ///Wison
        ///Hilly
        ///Cotte
        ///Close
        ///Loper
        ///Juanio
        ///Meson
        ///Willie
        ///Campbenn
        ///Jase
        ///Coley
        ///Jamy
        ///Bellee
        ///Rony
        ///Washy
        ///Braige
        ///Leson
        ///Dave
        ///Resell
        ///Riane
        ///Kere
        ///Roge
        ///Rooksell
        ///Scarly
        ///Rosson
        ///George
        ///Johnson
        ///Pauly
        ///Barnels
        ///Jamy
        ///Campbail
        ///Kelly
        ///Coxand
        ///Dorie
        ///Broberts
        ///Rona
        ///Jamith
        ///Mara
        ///Reson
        ///L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lastnames {
            get {
                return ResourceManager.GetString("lastnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon
        ///Phobos
        ///Deimos
        ///Io
        ///Europa
        ///Ganymede
        ///Callisto
        ///Amalthea
        ///Himalia
        ///Elara
        ///Pasiphae
        ///Sinope
        ///Lysithea
        ///Carme
        ///Ananke
        ///Leda
        ///Thebe
        ///Adrastea
        ///Metis
        ///Callirrhoe
        ///Themisto
        ///Megaclite
        ///Taygete
        ///Chaldene
        ///Harpalyke
        ///Kalyke
        ///Iocaste
        ///Erinome
        ///Isonoe
        ///Praxidike
        ///Autonoe
        ///Thyone
        ///Hermippe
        ///Aitne
        ///Eurydome
        ///Euanthe
        ///Euporie
        ///Orthosie
        ///Sponde
        ///Kale
        ///Pasithee
        ///Hegemone
        ///Mneme
        ///Aoede
        ///Thelxinoe
        ///Arche
        ///Kallichore
        ///Helike
        ///Carpo
        ///Eukelade
        ///Cyllene
        ///Kore
        ///Herse
        ///Dia
        ///Eirene
        ///Philophrosyne
        ///Eupheme
        ///Valetudo
        ///Pandia        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string orgs {
            get {
                return ResourceManager.GetString("orgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orion Wyke
        ///Halifax McRaven
        ///Cormac Hyden
        ///Elon Scofield
        ///Fafnir Jadin
        ///Preston Avison
        ///Holbrook Kerensky
        ///Jet Catlow
        ///Ulric Madi
        ///Nicol Gulsvig
        ///Luna Zahra
        ///Evelyn Bucanan
        ///Leah Solari
        ///Lyssa Carthen
        ///Kona Bowdoin
        ///Kirsten Hames
        ///Ariana Jackstadt
        ///Morgana Rackham
        ///Rosette Sharpey
        ///Luna Erikson
        ///Elon Hohstadt
        ///Ethan Alcantar
        ///Reid Iavarone
        ///Kiefer Thoran
        ///Gareth Holtz
        ///Ulric Hammacher
        ///Xerxes Kniffin
        ///Quentin Kingston
        ///Edison Mattix
        ///Uruk Steward
        ///Tessa Foxwell
        ///Heather Alessandro
        ///Xylona Zechiel
        ///Camden Sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string teachers {
            get {
                return ResourceManager.GetString("teachers", resourceCulture);
            }
        }
    }
}
